### ISSUE TITLE
Posts don't appear on blog

### ISSUE THREAD

**Issue by jeffrin** [ParitoshBh/grav-coder#10]
I followed the structure in the setup instructions and have my post saved in `~/www/html/user/pages/01.blog/blog-post-title/item.md`.

I can browse directly via the URL, but can't get it to show on the /blog page. Renaming the blog directory `02.blog` as suggested in [this thread](https://github.com/ParitoshBh/grav-coder/issues/4) didn't work, either.

**Comment by ParitoshBh** [comment]
Could you please list steps you followed? I am not able to reproduce the issue.

**Comment by aberusugi** [comment]
Change page type to "Item".

That works for me. Grav's admin panel doesn't default posts to Item under the Blog folder. I have to do this basically every time, or at least check it every time.

**Comment by ParitoshBh** [comment]
@jeffrin @aberusugi Are you using Grav Admin to setup the theme? Please note that I haven't tested setting up and configuring this theme via the admin plugin. If I can get a step by step instruction of what doesn't work as expected, I can certainly look into making this theme play more nicely with admin plugin.

**Comment by ParitoshBh** [comment]
Please reopen this issue with more information.
