### ISSUE TITLE
Default template issues

### ISSUE THREAD

**Issue by Japhys** [ParitoshBh/grav-coder#12]
I am very new to Grav so bear with me please :)

I just installed it yesterday, played around a bit and installed your lovely theme. I was able to set up a blog in no time, and it looks great. Thanks.

I also use the login plugin to make some pages private, also works effortless. However the register page and login page look kinda messed up (see attach). I think they use default page template? So I made some other pages and all content seems to be centered and breaks don't seem to work. Markdown like this is being shown on one single line. 

```
## test 1
### test 2
```

Am I missing something? Doing sonething wrong here? Hope you can help me out here.

![Screenshot(4)](https://user-images.githubusercontent.com/24695937/58379695-6c045500-7fa7-11e9-872c-aa21112dd7b0.png)

**Comment by ParitoshBh** [comment]
Were you able to get this working considering #13 workaround?

**Comment by Japhys** [comment]
Hi there,

No not yet. Grav is still pretty new to me (also I am not a coder :)) and I didn't have much time to dive into it yet. I suppose you didn't do much in terms of styling the 'default' template since you are not really using 'default'pages?
Can you point me in the right direction?

Kind regards

**Comment by Japhys** [comment]
I have honestly no idea what I am doing but I seem to have managed what I wanted

I removed "centered" from <section class="container"> in base.html.twig which aligns everything just like I wanted on normal pages but also on home, so I created a different class for the intro text on home

    margin: 0;
    position: absolute;
    top: 50%;
    left: 50%;
    -ms-transform: translate(-50%, -50%);
    transform: translate(-50%, -50%);
    text-align: center;
