### ISSUE TITLE
Page navigation broken

### ISSUE THREAD

**Issue by aberusugi** [ParitoshBh/grav-coder#16]
Might be due to an update from Grav, but page navigation is broken. The "Older" button goes to https://page:2 instead of https://mysite.com/page:2

**Comment by ParitoshBh** [comment]
Can you please share Grav version you are using?

**Comment by ParitoshBh** [comment]
My [personal website](https://paritoshbh.me/) was on Grav version 1.6.11 and updated to 1.6.17. Pagination is working just fine.

**Comment by aberusugi** [comment]
Sorry for the late reply:

Grav v1.6.17 - Admin v1.9.11

https://aberu.gg is my site - need to change the favicon, still newish made site btw.

**Comment by ParitoshBh** [comment]
Pushed a new release v0.1.5 fixing this. Please test again!

**Comment by aberusugi** [comment]
Sorry for late reply, I always forget to check my notifications here. The update fixed everything. Thanks!

**Comment by aberusugi** [comment]
Oh, just clicked "Newer" and the same problem happens, the same fix likely needs to be replicated for the newer button as it was for the older button.

**Comment by aberusugi** [comment]
Problem still exists today, but in the reverse.

https://aberu.gg/page:2

Head there, and then click "newer" button, and this is what it directs to:

https://page:1/

**Comment by ParitoshBh** [comment]
Sorry, that's completely my fault. I fixed the _Older_ navigation slug and not the _Newer_ one. Pushed a new release fixing this - https://github.com/ParitoshBh/grav-coder/releases/tag/0.1.6

Hopefully navigation will work as expected now :)

**Comment by aberusugi** [comment]
This worked! Thank you much!
