### ISSUE TITLE
centered class display = flex

### ISSUE THREAD

**Issue by Alley041** [ParitoshBh/grav-coder#17]
hi, in the .centered class, display is set on flex
now i build a contact form page, and this is that page:

http://s7.picofile.com/file/8377799168/screencapture_localhost_2_contact_1573390034551.png

when i set Display=Block in custom.css, this fixes contact page but destroy first page - about page - 
sorry for bad english :|

**Comment by ParitoshBh** [comment]
Hey,

The `.centered` class is the default to get the view you see in demo. To override any of the theme's CSS please follow instructions here https://github.com/ParitoshBh/grav-coder#customizations
