### ISSUE TITLE
FontAwesome fonts do not appear on all pages

### ISSUE THREAD

**Issue by varun-ramraj** [ParitoshBh/grav-coder#21]
Greetings! Thanks so much for making this theme.

With the latest update, it seems as though fontawesome fonts are not appearing on all pages. I see they appear on Error pages, but not the other ones.

I'm primarily trying to just get the default Github and Linked In icons appearing in the footer. Please let me know if you need more information. I have attached screenshots from my site to show this behaviour:

Normal front page; note the separator dots appear at the bottom (above the copyright), but the three icons are blank.

<img width="1033" alt="Screenshot 2020-03-28 at 21 23 42" src="https://user-images.githubusercontent.com/9196495/77834163-76006280-713a-11ea-8060-715ad706ff23.png">

The error page; note that the icons appear as expected at the bottom:

<img width="995" alt="Screenshot 2020-03-28 at 21 23 57" src="https://user-images.githubusercontent.com/9196495/77834176-8dd7e680-713a-11ea-809d-60e08956f730.png">

Many thanks!

**Comment by ParitoshBh** [comment]
Looks like whatever plugin you're using for displaying the consent form is conflicting with favicons in footer. If I click on the agree button, the page (re)loads and favicons appear just fine the first time but disappear in subsequent loads.

Can you try disabling whatever plugin you're using and try again?

**Comment by varun-ramraj** [comment]
Thanks @ParitoshBh , that seems to work. I am using a different cookie control mechanism and the page seems to load correctly both before and after accepting.

FYI, I've updated your code to use the latest fontawesome and to be able to render the whole set, instead of just what is part of the "fab" i-class. If you'd like, I can issue a pull request.

**Comment by ParitoshBh** [comment]
Sure, that'd be nice! I am closing this issue, feel free to create a PR :smile:
