### ISSUE TITLE
after grav update - had to copy default.html.twig to home.html.twig

### ISSUE THREAD

**Issue by Krisselack** [ParitoshBh/grav-coder#22]
In html/user/themes/grav-coder/templates/
Then it worked. Previously I got a 400 file not found error.

**Comment by ParitoshBh** [comment]
I just upgraded from version 1.4.8 to 1.6.26 and didn't face any issue. Can you please provide some more information?
- What was the version before?
- To which version did you upgrade?
- Did you make any edits to theme files previously?
- Anything else that you did to get the theme working initially?

**Comment by ParitoshBh** [comment]
Please reopen this issue with more information.

**Comment by Krisselack** [comment]
Maybe it is my specific setup, thank you! Will check at the next update.

**Comment by Krisselack** [comment]
After running the latest grav update, my setup broke. I reinstalled everything new including your theme. 
I copied my old files into the user folder and edited the config there. I did not change anything in the /user/themes/grav-coder folder and everything worked as before. Thanks again!
