### ISSUE TITLE
Content is load 'sideways'

### ISSUE THREAD

**Issue by tomlawesome** [ParitoshBh/grav-coder#28]
Hello, firstly -- thank you for porting & modifying such a fabulous theme! It's great. 

I'm struggling to move my site to the theme though, because all the markdown content in page loads sideways? 

![image](https://user-images.githubusercontent.com/76453276/140744628-9b5d050a-03df-4a83-894f-82455511bd1c.png)

![image](https://user-images.githubusercontent.com/76453276/140744738-bc85f22e-74ee-43b9-950d-e4db1a3e4868.png)

**Comment by ParitoshBh** [comment]
Did you try putting content in div? Homepage is special and you need to follow the structure that's provided.

**Comment by ParitoshBh** [comment]
Closing this issue due to non-activity. If you still have the issue please re-open it (with details for reproducing).
