### ISSUE TITLE
How to create the home page

### ISSUE THREAD

**Issue by sebasvisser** [ParitoshBh/grav-coder#4]
How can I recreate your home page? What template should I use, and what content does it have on your demo?

Thanks for your help.

**Comment by ParitoshBh** [comment]
Sorry for the late response, I didn't have access to computer for the past 4 days. There's isn't any documentation for setting up the demo (nor any dummy content) as of now. I will look into adding the same!

**Comment by ParitoshBh** [comment]
Once you have,
- Installed Grav framework
- Installed this theme
- Followed the theme [setup instructions](https://github.com/ParitoshBh/grav-coder#setup)

The missing part that needs to be done is,
1. Rename the `01.home` directory to `home` under `user/pages/`
1. Delete contents of `default.md` in that directory and add following,
   ```html 
   <div class="about">
     <h1>Your Name</h1>
     <h2>Your sub heading</h2>
   </div>
   ```
1. For the menu item `blog`, simply create a `02.blog` directory under `user/pages/` (with some content in it)
1. For further customization (social media icons at bottom, title bar, etc) please refer to [Customizations section](https://github.com/ParitoshBh/grav-coder#customizations).

**Comment by Krisselack** [comment]
On my system, I had to change the home.md in the home folder.

**Comment by ParitoshBh** [comment]
Added some instructions on setting up the theme - refer https://github.com/ParitoshBh/grav-coder/tree/dev-fixes

**Comment by jeffrin** [comment]
I can't get posts to appear on the blog. I followed the structure in the setup instructions and have my post saved in `~/www/html/user/pages/01.blog/blog-post-title/item.md`. 

I can browse directly to the post, but can't get it to show on the /blog page. Renaming the blog directory `02.blog` as suggested on this thread didn't work, either.
