### ISSUE TITLE
More Sections possible?

### ISSUE THREAD

**Issue by Krisselack** [ParitoshBh/grav-coder#5]
Hi, I really like the minimalistic style of the theme. 
I would like to adapt it a bit though: 
- [x] I would like to include a round image at the homepage (as in the original hugo theme) 

I would like to include an about section (legal requirement) and possibly a second Blog Section. 
Would that be possible, or would I have to stick with your version? 
Thanks!

**Comment by ParitoshBh** [comment]
> I would like to include a round image at the homepage (as in the original hugo theme)

Implementing this shouldn't be too hard. As of now I am running a little busy but I'll see if an update can be pushed.

> I would like to include an about section (legal requirement) and possibly a second Blog Section.

Would these go in the top navbar? An about section is planned. For the second blog section, you can as it is create another menu item for second blog by simply by creating a 03.blog3 directory under user/pages/ (with some content in it).

> Would that be possible, or would I have to stick with your version?

Nope, you don't have to stick to my version. This version is what I think is sufficient for me but I am open to suggestion for new features!

**Comment by Krisselack** [comment]
Thanks, I was able to get more sections online. I decided to use your theme, because I found it prettier. Some issues I encountered: the category blog doesn't work. Some contents (default.md, if I recall correctly) are displayed horizontally (this is also an issue with the default install demo entries). Also encoding causes issues (Umlauts and line feeds) for me.

**Comment by ParitoshBh** [comment]
> Some contents (default.md, if I recall correctly) are displayed horizontally (this is also an issue with the default install demo entries).

I have updated the instructions for correctly setting up the homepage (and so it doesn't mess up the default entries). Refer here https://github.com/ParitoshBh/grav-coder/tree/dev-fixes#setup

> Also encoding causes issues (Umlauts and line feeds) for me.

Is there a way to reproduce it? It'd be great if you can you share steps!

**Comment by ParitoshBh** [comment]
@Krisselack Added a page in wiki for [creating homepage with an image](https://github.com/ParitoshBh/grav-coder/wiki/Example-Homepage-Setup). You should be able to use the code as it is (no changes required to the theme itself).
