### ISSUE TITLE
Icon distorted - researchgate

### ISSUE THREAD

**Issue by Krisselack** [ParitoshBh/grav-coder#6]
I use the researchgate icon from font awesome, but it is not displayed correctly. 
https://github.com/FortAwesome/Font-Awesome/issues/14256#issuecomment-439730551

**Comment by ParitoshBh** [comment]
Tried it. The icon is _thickned_ and as such appears distorted. I'll look into this and see if there's a better way of handling it.

**Comment by ParitoshBh** [comment]
Fix will be pushed as part of next update!

**Comment by Krisselack** [comment]
thanks!

**Comment by Krisselack** [comment]
btw, now it works flawlessly, thank you!
