### ISSUE TITLE
How do I update the copyright year to 2019?

### ISSUE THREAD

**Issue by jeffrin** [ParitoshBh/grav-coder#9]

**Comment by jeffrin** [comment]
Sometimes you need to post the question for the answer to reveal itself. 

`vim ~/www/html/user/themes/grav-coder/templates/partials/vim footer.html.twig` 

Thanks for the great theme!

**Comment by ParitoshBh** [comment]
In case you are still interested, I have updated the theme to always use current year. Also, you can define a start year as well (refer readme).
